package lk.ac.icbt.sunrisedental.dao;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.LocalTime;
import lk.ac.icbt.sunrisedental.model.Appointment;
import lk.ac.icbt.sunrisedental.model.AppointmentStatus;
import lk.ac.icbt.sunrisedental.model.Dentist;
import lk.ac.icbt.sunrisedental.model.Patient;
import lk.ac.icbt.sunrisedental.model.Treatment;
import lk.ac.icbt.sunrisedental.util.DatabaseConnectionFactory;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class JdbcAppointmentDaoTest {
    private final JdbcAppointmentDao appointments = new JdbcAppointmentDao();
    private final LocalDate date = LocalDate.of(2026, 9, 10);
    private final Dentist dentist = new Dentist(1, "Dr Perera", true);
    private final Treatment treatment = new Treatment(1, "Cleaning", new BigDecimal("2500.00"), true);

    @BeforeEach
    void createSchema() throws Exception {
        try (Connection connection = DatabaseConnectionFactory.getInstance().getConnection(); Statement statement = connection.createStatement()) {
            statement.executeUpdate("DROP TABLE IF EXISTS appointments");
            statement.executeUpdate("DROP TABLE IF EXISTS patients");
            statement.executeUpdate("DROP TABLE IF EXISTS dentists");
            statement.executeUpdate("DROP TABLE IF EXISTS treatments");
            statement.executeUpdate("CREATE TABLE patients (patient_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, full_name VARCHAR(100) NOT NULL, address VARCHAR(255) NOT NULL, contact_number VARCHAR(30) NOT NULL)");
            statement.executeUpdate("CREATE TABLE dentists (dentist_id BIGINT PRIMARY KEY, full_name VARCHAR(100) NOT NULL, active BOOLEAN NOT NULL)");
            statement.executeUpdate("CREATE TABLE treatments (treatment_id BIGINT PRIMARY KEY, treatment_name VARCHAR(100) NOT NULL, price DECIMAL(12,2) NOT NULL, active BOOLEAN NOT NULL)");
            statement.executeUpdate("CREATE TABLE appointments (appointment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, appointment_number VARCHAR(20) NOT NULL UNIQUE, patient_id BIGINT NOT NULL, dentist_id BIGINT NOT NULL, treatment_id BIGINT NOT NULL, appointment_date DATE NOT NULL, appointment_time TIME NOT NULL, status VARCHAR(20) NOT NULL)");
            statement.executeUpdate("INSERT INTO dentists VALUES (1, 'Dr Perera', TRUE)");
            statement.executeUpdate("INSERT INTO treatments VALUES (1, 'Cleaning', 2500.00, TRUE)");
        }
    }

    @Test
    void savesFindsUpdatesFiltersAndCancelsAnAppointment() {
        Appointment saved = appointments.save(new Appointment(0, "APT-DAO-001", new Patient(0, "Asha Silva", "Kandy", "0711111111"), dentist, treatment, date, LocalTime.of(9, 0), AppointmentStatus.ACTIVE));

        assertTrue(saved.id() > 0);
        assertTrue(saved.patient().id() > 0);
        assertTrue(appointments.hasActiveSlot(1, date, LocalTime.of(9, 0), null));
        assertEquals("Asha Silva", appointments.findByNumber("APT-DAO-001").orElseThrow().patient().fullName());

        Appointment updated = new Appointment(saved.id(), saved.appointmentNumber(), new Patient(saved.patient().id(), "Asha Silva", "Matale", "0722222222"), dentist, treatment, date, LocalTime.of(10, 0), AppointmentStatus.ACTIVE);
        appointments.update(updated);

        assertEquals("Matale", appointments.findByNumber("APT-DAO-001").orElseThrow().patient().address());
        assertEquals(1, appointments.findAll(date, 1L).size());
        assertFalse(appointments.hasActiveSlot(1, date, LocalTime.of(9, 0), null));

        appointments.cancel("APT-DAO-001");
        assertEquals(AppointmentStatus.CANCELLED, appointments.findByNumber("APT-DAO-001").orElseThrow().status());
    }
}
